---
kind: pipeline
name: default

steps:
- name: amd64
  image: clickable/ci-20.04-amd64
  commands:
  - clickable build --clean

- name: arm64
  image: clickable/ci-20.04-arm64
  commands:
  - clickable build --clean

- name: armhf
  image: clickable/ci-20.04-armhf
  commands:
    - clickable build --clean

- name: push-release
  depends_on:
  - amd64
  - arm64
  - armhf
  image: plugins/gitea-release
  when:
    ref:
    - refs/tags/v*
  settings:
    api_key:
      from_secret: release_push_key
    base_url: https://git.agnos.is/
    files: "**/*.click"

- name: open-store-publish
  depends_on:
  - push-release
  when:
    ref:
    - refs/tags/v*
  image: clickable/ci-20.04-armhf
  commands:
    - clickable publish --arch arm64 -- ${DRONE_COMMIT_MESSAGE}
    - clickable publish --arch amd64 -- ${DRONE_COMMIT_MESSAGE}
    - clickable publish --arch armhf -- ${DRONE_COMMIT_MESSAGE}
  environment:
   OPENSTORE_API_KEY:
      from_secret: openstore_api_key
