---
kind: pipeline
name: default

steps:

  - name: test
    image: clickable/ci-20.04-amd64
    commands:
      - cargo test --no-default-features

  - name: amd64
    image: clickable/ci-ut24.04-1.x-amd64
    depends_on:
      - test
    commands:
      - clickable build --clean

  - name: arm64
    image: clickable/ci-ut24.04-1.x-arm64
    depends_on:
      - test
    commands:
      - clickable build --clean

  - name: armhf
    image: clickable/ci-ut24.04-1.x-armhf
    depends_on:
      - test
    commands:
      - clickable build --clean

  - name: pre-release
    depends_on:
      - amd64
      - arm64
      - armhf
    image: plugins/gitea-release
    when:
      ref:
        - "refs/tags/rc-*"
    settings:
      api_key:
        from_secret: release_push_key
      base_url: https://git.agnos.is/
      prerelease: true
      files:
        - build/x86_64-linux-gnu/app/keepassrx.projectmoon_*.click
        - build/aarch64-linux-gnu/app/keepassrx.projectmoon_*.click
        - build/arm-linux-gnueabihf/app/keepassrx.projectmoon_*.click

  - name: production-release
    depends_on:
      - amd64
      - arm64
      - armhf
    image: plugins/gitea-release
    when:
      ref:
        - "refs/tags/v*"
    settings:
      api_key:
        from_secret: release_push_key
      base_url: https://git.agnos.is/
      prerelease: false
      files:
        - build/x86_64-linux-gnu/app/keepassrx.projectmoon_*.click
        - build/aarch64-linux-gnu/app/keepassrx.projectmoon_*.click
        - build/arm-linux-gnueabihf/app/keepassrx.projectmoon_*.click

  - name: open-store-publish
    image: clickable/ci-20.04-amd64
    depends_on:
      - production-release
    when:
      ref:
        - "refs/tags/v*"
    commands:
      - |
        clickable publish --arch arm64 -- "Release ${DRONE_COMMIT_REF}"
      - |
        clickable publish --arch amd64 -- "Release ${DRONE_COMMIT_REF}"
      - |
        clickable publish --arch armhf -- "Release ${DRONE_COMMIT_REF}"
    environment:
      OPENSTORE_API_KEY:
        from_secret: openstore_api_key
