on: [push]
jobs:
  build-amd64:
    runs-on: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Clickable
        run: pipx install clickable-ut

      - name: Build
        run: clickable build --clean

      - name: Test
        run: clickable test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: amd64
          path: build/x86_64-linux-gnu/app/keepassrx.projectmoon_*.click
