on: [push]
jobs:
  license-check:
    runs-on: docker
    container:
      image: rust:1.91.0
    steps:
      - name: Add NodeJS deb repo
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

      - name: Install NodeJS
        run: apt update && apt install -y nodejs

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: https://github.com/Swatinem/rust-cache@v2

      - name: Install Cargo Deny
        run: cargo install cargo-deny

      - name: License Check
        run: cargo deny check licenses

      - name: Install Cargo About
        run: cargo install cargo-about

      - name: Generate licenses.html
        run: cargo about generate about.hbs > keepass-rx/assets/licenses.html

      - name: Upload licenses.html
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: licenses.html
          path: keepass-rx/keepass-rx/assets/licenses.html

  test:
    runs-on: docker
    container:
      image: clickable/ci-ut24.04-1.x-amd64
    steps:
      - name: Add NodeJS deb repo
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

      - name: Install NodeJS
        run: apt update && apt install -y nodejs

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: https://github.com/Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --no-default-features

  build-amd64:
    needs: [test, license-check]
    runs-on: docker
    container:
      image: clickable/ci-ut24.04-1.x-amd64
    steps:
      - name: Add NodeJS deb repo
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

      - name: Install NodeJS
        run: apt update && apt install -y nodejs

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: https://github.com/Swatinem/rust-cache@v2

      - name: Download licenses.html
        uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          name: licenses.html
          path: keepass-rx/keepass-rx/assets/licenses.html

      - name: Build
        run: clickable build --clean

      - name: Upload Artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: keepassrx-ci-amd64
          path: build/x86_64-linux-gnu/app/keepassrx.projectmoon_*.click

  build-arm64:
    needs: [test, license-check]
    runs-on: docker
    container:
      image: clickable/ci-ut24.04-1.x-arm64
    steps:
      - name: Add NodeJS deb repo
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

      - name: Install NodeJS
        run: apt update && apt install -y nodejs

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: https://github.com/Swatinem/rust-cache@v2

      - name: Download licenses.html
        uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          name: licenses.html
          path: keepass-rx/keepass-rx/assets/licenses.html

      - name: Build
        run: clickable build --clean

      - name: Upload Artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: keepassrx-ci-arm64
          path: build/aarch64-linux-gnu/app/keepassrx.projectmoon_*.click

  build-armhf:
    needs: [test, license-check]
    runs-on: docker
    container:
      image: clickable/ci-ut24.04-1.x-armhf
    steps:
      - name: Add NodeJS deb repo
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

      - name: Install NodeJS
        run: apt update && apt install -y nodejs

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: https://github.com/Swatinem/rust-cache@v2

      - name: Download licenses.html
        uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          name: licenses.html
          path: keepass-rx/keepass-rx/assets/licenses.html

      - name: Build
        run: clickable build --clean

      - name: Upload Artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: keepassrx-ci-armhf
          path: build/arm-linux-gnueabihf/app/keepassrx.projectmoon_*.click
